import { GuestAuthProvider } from "@/context/auth-guest";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Asphere Apps Portal",
  description: "Generated by Asphere Apps",
};

export default function GuestLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GuestAuthProvider>
      <div>{children}</div>
    </GuestAuthProvider>
  );
}
